module.exports = {
  env: {
    CONTENTFUL_SPACE_ID: process.env.CONTENTFUL_SPACE_ID,
    CONTENTFUL_ACCESS_TOKEN: process.env.CONTENTFUL_ACCESS_TOKEN,
    SQUIDEX_CLIENT_SECRET: process.env.SQUIDEX_CLIENT_SECRET,
  },
};
