import type { GetStaticProps, NextPage } from 'next';
import Head from 'next/head';

export const getStaticProps: GetStaticProps = async () => {
    const response = await fetch(`${process.env.HOST}/api/recipes`);
    const data = await response.json();

    return {
        props: {
            data,
        },
    };
};

const Home: NextPage = (props) => {
    console.log(props);

    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <h1>Flatbread</h1>
        </div>
    );
};

export default Home;
