name: Main Checks
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  Lint-Code:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set node to v${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache packages
      uses: actions/cache@v2
      with:
        path: ${{ github.workspace }}/node_modules
        key: ${{ runner.OS }}-${{ matrix.node-version }}-node-${{ hashFiles('**/yarn.lock') }}
    - name: Install packages
      run: yarn install --frozen-lockfile
    - name: Lint code
      run: yarn lint
  Build-App:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set node to v${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache packages
      uses: actions/cache@v2
      with:
        path: ${{ github.workspace }}/node_modules
        key: ${{ runner.OS }}-${{ matrix.node-version }}-node-${{ hashFiles('**/yarn.lock') }}
    - name: Cache app build
      uses: actions/cache@v2
      with:
        path: ${{ github.workspace }}/.next/cache
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}
    - name: Install packages
      run: yarn install --frozen-lockfile
    - name: Build app
      run: yarn build
      env:
        MONGODB_COLLECTION_COURSE_TYPES: ${{ secrets.MONGODB_COLLECTION_COURSE_TYPES }}
        MONGODB_COLLECTION_CUISINES: ${{ secrets.MONGODB_COLLECTION_CUISINES }}
        MONGODB_COLLECTION_DIETARY_RESTRICTIONS: ${{ secrets.MONGODB_COLLECTION_DIETARY_RESTRICTIONS }}
        MONGODB_COLLECTION_DISH_TYPES: ${{ secrets.MONGODB_COLLECTION_DISH_TYPES }}
        MONGODB_COLLECTION_INGREDIENT_NAMES: ${{ secrets.MONGODB_COLLECTION_INGREDIENT_NAMES }}
        MONGODB_COLLECTION_INGREDIENT_UNITS: ${{ secrets.MONGODB_COLLECTION_INGREDIENT_UNITS }}
        MONGODB_COLLECTION_RECIPES: ${{ secrets.MONGODB_COLLECTION_RECIPES }}
        MONGODB_DB: ${{ secrets.MONGODB_DB }}
        MONGODB_URL: ${{ secrets.MONGODB_URL }}
  Check-Dependencies:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set node to v${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache packages
      uses: actions/cache@v2
      with:
        path: ${{ github.workspace }}/node_modules
        key: ${{ runner.OS }}-${{ matrix.node-version }}-node-${{ hashFiles('**/yarn.lock') }}
    - name: Install packages
      run: yarn install --frozen-lockfile
    - name: Check dependencies
      run: npx depcheck
